[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' https://cloud.umami.is.com https://unpkg.com;
      style-src 'self' https://cdnjs.cloudflare.com;
      connect-src 'self';
      img-src 'self' data:;
      font-src 'self' https://cdnjs.cloudflare.com;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
      frame-ancestors 'none';
    """
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"